apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default
  labels:
    app: todo-list
stringData:
  MYSQL_DATABASE: tododb
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_ROOT_PASSWORD: rootpassword
