version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: tododb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./todo-list-backend
    environment:
      MYSQL_DATABASE_USER: user
      MYSQL_DATABASE_PASSWORD: password
      MYSQL_DATABASE_DB: tododb
      MYSQL_DATABASE_HOST: db
      SECRET_KEY: supersecretkey
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["python", "app.py"]

  frontend:
    build: ./todo-list-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
